// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElAffix: typeof import('element-plus/es')['ElAffix']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    Ellipsis: typeof import('./src/components/custom/Ellipsis.vue')['default']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    HomePage: typeof import('./src/components/HomePage/index.vue')['default']
    Loading: typeof import('element-plus/es')['ElLoadingDirective']
    MultiEllipsis: typeof import('./src/components/custom/MultiEllipsis.vue')['default']
    MusicController: typeof import('./src/components/MusicController/index.vue')['default']
    My: typeof import('./src/components/My/index.vue')['default']
    Navbar: typeof import('./src/components/Navbar/index.vue')['default']
    Playlist: typeof import('./src/components/Playlist/index.vue')['default']
    ReactiveStyle: typeof import('./src/components/MusicController/reactiveStyle.vue')['default']
    RecommendMusic: typeof import('./src/components/HomePage/RecommendMusic.vue')['default']
    RecommendPlaylist: typeof import('./src/components/HomePage/RecommendPlaylist.vue')['default']
    Sider: typeof import('./src/components/Sider/index.vue')['default']
  }
}

export { }
