// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElAffix: typeof import('element-plus/es')['ElAffix']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    Ellipsis: typeof import('./src/components/custom/Ellipsis.vue')['default']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    HomePage: typeof import('./src/components/HomePage/index.vue')['default']
    MusicController: typeof import('./src/components/MusicController/index.vue')['default']
    My: typeof import('./src/components/My/index.vue')['default']
    Navbar: typeof import('./src/components/Navbar/index.vue')['default']
    Playlist: typeof import('./src/components/Playlist/index.vue')['default']
  }
}

export { }
